check profiler logs

diff --git a/test/dlc_tests/container_tests/bin/testTensorFlow b/test/dlc_tests/container_tests/bin/testTensorFlow
--- a/test/dlc_tests/container_tests/bin/testTensorFlow
+++ b/test/dlc_tests/container_tests/bin/testTensorFlow
@@ -17,9 +17,18 @@ TRAINING_LOG=${LOG_DIR}/${KERAS_BACKEND}_train_mnist.log
 
 echo "Training mnist using $KERAS_BACKEND... This may take a few minutes. You can follow progress on the log file : $TRAINING_LOG"
 set +e
+
+[ -d $LOG_DIR ] && echo "Cleanning existing logs" && rm -rf $LOG_DIR
+
 python ${BIN_DIR}/testTensorflow.py >$TRAINING_LOG 2>&1
 RETURN_VAL=`echo $?`
 set -e
+
+echo "Verify tensorfolow profiler can generate logs."
+LOG_RESULT=$(find $LOG_DIR -name "*.pb")
+echo "Checking the logs result: $LOG_RESULT"
+
+[ -z "$LOG_RESULT" ] && echo "Cannot find Profiler logs!" && exit 1
 
 if [ ${RETURN_VAL} -eq 0 ]; then
     echo "Training mnist Complete using $KERAS_BACKEND."
