test exit status tensorflow

diff --git a/test/dlc_tests/container_tests/bin/testSmdebug b/test/dlc_tests/container_tests/bin/testSmdebug
--- a/test/dlc_tests/container_tests/bin/testSmdebug
+++ b/test/dlc_tests/container_tests/bin/testSmdebug
@@ -53,6 +53,14 @@ if [[ $FRAMEWORK == "tensorflow" ]]; then
     pytest mock/tests/${FRAMEWORK} \
                             -k "not test_keras and not test_mnist_s3 and not test_mnist_s3_multi_save_configs" \
                             --ignore=mock/tests/mxnet/test_training_end.py
+    exit_code=$?
+    if [ "$exit_code" -eq "0" ]
+    then
+        echo "SMDebug framework tests succeeded"
+    else
+        echo "SMDebug framework tests failed"
+        exit 1
+    fi
 else
     for test_file in mock/tests/${FRAMEWORK}/*
     do
