exit code for gradtape

diff --git a/test/dlc_tests/container_tests/bin/testSmdebug b/test/dlc_tests/container_tests/bin/testSmdebug
--- a/test/dlc_tests/container_tests/bin/testSmdebug
+++ b/test/dlc_tests/container_tests/bin/testSmdebug
@@ -59,7 +59,7 @@ if [[ $FRAMEWORK == "tensorflow" ]]; then
         echo "SMDebug framework tests succeeded"
     else
         echo "SMDebug framework tests failed"
-        exit 1
+        exit $exit_code
     fi
 else
     for test_file in mock/tests/${FRAMEWORK}/*
@@ -79,7 +79,7 @@ else
                 echo "SMDebug no tests collected: $test_file"
             else
                 echo "SMDebug test failed: $test_file"
-                exit 1
+                exit $exit_code
             fi
         fi
     done
@@ -96,11 +96,21 @@ if [ ! ${ZCC_TEST_NAME[$FRAMEWORK]} ]; then
     exit 1
 fi
 if [[ ${FRAMEWORK} == "tensorflow2" ]]; then
+    echo "Running Gradtape test"
     if [ "$(printf '%s\n' "0.7.2" "$SMDEBUG_RELEASE_TAG" | sort -V | head -n1)" = "0.7.2" ]; then
         if [ "$(printf '%s\n' "0.8.0" "$SMDEBUG_RELEASE_TAG" | sort -V | head -n1)" = "0.8.0" ]; then
             pytest mock/tests/zero_code_change/test_${FRAMEWORK}_gradtape_integration.py
+            exit_code=$?
         else
             python mock/tests/zero_code_change/${FRAMEWORK}_gradtape_integration_tests.py
+            exit_code=$?
+        fi
+        if [ "$exit_code" -eq "0" ]
+        then
+            echo "SMDebug gradtape integration test succeeded"
+        else
+            echo "SMDebug gradtape integration test failed"
+            exit $exit_code
         fi
     fi
 fi
