exit 1 when failed to create profiler

diff --git a/test/dlc_tests/container_tests/bin/testTensorBoard b/test/dlc_tests/container_tests/bin/testTensorBoard
--- a/test/dlc_tests/container_tests/bin/testTensorBoard
+++ b/test/dlc_tests/container_tests/bin/testTensorBoard
@@ -1,9 +1,16 @@
 #!/bin/bash
-
+  
 HOME_DIR=/test
 BIN_DIR=${HOME_DIR}/bin
-LOG_DIR=${HOME_DIR}/logs
+LOG_DIR=${HOME_DIR}/logs/train/plugins/profile
 
-python ${BIN_DIR}/testTensorBoard.py || exit 1
+[ -d $LOG_DIR ] && echo "Cleanning existing logs" && rm -rf $LOG_DIR
+
+python testTensorBoard.py || exit 1
+
+LOG_RESULT=$(find $LOG_DUR -name "*.pb")
+echo "Checking the logs result: $LOG_RESULT"
+
+[ -z "$LOG_RESULT" ] && echo "Cannot find Profiler logs!" && exit 1
 
 exit 0
