more

diff --git a/test/dlc_tests/container_tests/bin/efa/test_nccl_tests_using_efa b/test/dlc_tests/container_tests/bin/efa/test_nccl_tests_using_efa
--- a/test/dlc_tests/container_tests/bin/efa/test_nccl_tests_using_efa
+++ b/test/dlc_tests/container_tests/bin/efa/test_nccl_tests_using_efa
@@ -59,15 +59,16 @@ check_efa_nccl_all_reduce(){
         -x PATH -x LD_LIBRARY_PATH=${CUDA_HOME}/lib:${CUDA_HOME}/lib64:$LD_LIBRARY_PATH \
         -x NCCL_SOCKET_IFNAME=^lo --mca pml ^cm --mca btl tcp,self --mca btl_tcp_if_exclude lo,docker0 --bind-to none \
         /all_reduce_perf -b 8 -e 1G -f 2 -g 1 -c 1 -n 100
-    # cat $TRAINING_LOG
-    # RETURN_VAL=${PIPESTATUS[0]}
-    # if [ ${RETURN_VAL} -eq 0 ]; then
-    #     echo "***************************** check_efa_nccl_all_reduce passed *****************************"
-    # else
-    #     echo "***************************** check_efa_nccl_all_reduce failed *****************************"
-    # fi
-    # validate_all_reduce_performance_logs
-    # check_efa_nccl_all_reduce_performance
+    
+    RETURN_VAL=${PIPESTATUS[0]}
+    cat $TRAINING_LOG
+    if [ ${RETURN_VAL} -eq 0 ]; then
+        echo "***************************** check_efa_nccl_all_reduce passed *****************************"
+    else
+        echo "***************************** check_efa_nccl_all_reduce failed *****************************"
+    fi
+    validate_all_reduce_performance_logs
+    check_efa_nccl_all_reduce_performance
 }
 
 check_efa_nccl_all_reduce
