fail cpu build intentionally

diff --git a/pytorch/training/docker/2.4/py3/Dockerfile.cpu b/pytorch/training/docker/2.4/py3/Dockerfile.cpu
--- a/pytorch/training/docker/2.4/py3/Dockerfile.cpu
+++ b/pytorch/training/docker/2.4/py3/Dockerfile.cpu
@@ -39,145 +39,145 @@ RUN apt-get update \
 
 FROM base_image AS common
 
-LABEL maintainer="Amazon AI"
-LABEL dlc_major_version="1"
-
-ARG PYTHON
-ARG PYTHON_VERSION
-
-ARG MINIFORGE3_VERSION
-ARG OPEN_MPI_VERSION
-
-# This arg required to stop docker build waiting for region configuration while installing tz data from ubuntu 20
-ARG DEBIAN_FRONTEND=noninteractive
-
-ENV LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}"
-ENV LD_LIBRARY_PATH="/opt/conda/lib:${LD_LIBRARY_PATH}"
-ENV LD_LIBRARY_PATH="/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}"
-ENV PATH="/opt/conda/bin:${PATH}"
-
-# Python won’t try to write .pyc or .pyo files on the import of source modules
-# Force stdin, stdout and stderr to be totally unbuffered. Good for logging
-ENV PYTHONDONTWRITEBYTECODE=1
-ENV PYTHONUNBUFFERED=1
-ENV PYTHONIOENCODING=UTF-8
-ENV LANG=C.UTF-8
-ENV LC_ALL=C.UTF-8
-
-ENV DLC_CONTAINER_TYPE=training
-WORKDIR /
-
-RUN apt-get update \
- && apt-get -y upgrade --only-upgrade systemd \
- && apt-get install -y --no-install-recommends \
-    automake \
-    build-essential \
-    ca-certificates \
-    cmake \
-    curl \
-    emacs \
-    git \
-    jq \
-    libcurl4-openssl-dev \
-    libglib2.0-0 \
-    libgl1-mesa-glx \
-    libsm6 \
-    libssl-dev \
-    libxext6 \
-    libxrender-dev \
-    zlib1g-dev \
-    unzip \
-    vim \
-    wget \
- && apt-get clean \
- && rm -rf /var/lib/apt/lists/*
-
-# Install Open MPI
-RUN wget https://www.open-mpi.org/software/ompi/v4.1/downloads/openmpi-${OPEN_MPI_VERSION}.tar.gz \
- && gunzip -c openmpi-${OPEN_MPI_VERSION}.tar.gz | tar xf - \
- && cd openmpi-${OPEN_MPI_VERSION} \
- && ./configure --prefix=/home/.openmpi \
- && make all install \
- && cd .. \
- && rm openmpi-${OPEN_MPI_VERSION}.tar.gz \
- && rm -rf openmpi-${OPEN_MPI_VERSION}
-
-# Install OpenSSH for MPI to communicate between containers, allow OpenSSH to talk to containers without asking for confirmation
-RUN apt-get update \
- && apt-get install -y --no-install-recommends openssh-client openssh-server \
- && mkdir -p /var/run/sshd \
- && cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new \
- && echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new \
- && mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config \
- && apt-get clean \
- && rm -rf /var/lib/apt/lists/*
-
-# Configure OpenSSH so that nodes can communicate with each other
-RUN mkdir -p /var/run/sshd \
- && sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
-
-RUN rm -rf /root/.ssh/ \
- && mkdir -p /root/.ssh/ \
- && ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa \
- && cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys \
- && printf "Host *\n StrictHostKeyChecking no\n" >> /root/.ssh/config
-
-# For conda ssl verification
-ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
-RUN curl -L -o ~/miniforge3.sh https://github.com/conda-forge/miniforge/releases/download/${MINIFORGE3_VERSION}/Miniforge3-${MINIFORGE3_VERSION}-Linux-x86_64.sh \
- && chmod +x ~/miniforge3.sh \
- && ~/miniforge3.sh -b -p /opt/conda \
- && rm ~/miniforge3.sh
-
-RUN pip install --no-cache-dir --upgrade pip --no-cache-dir --trusted-host pypi.org --trusted-host files.pythonhosted.org \
- && ln -s /opt/conda/bin/pip /usr/local/bin/pip3
-
-# Install common conda packages
-RUN /opt/conda/bin/mamba install -y -c conda-forge \
-    python=$PYTHON_VERSION \
-    cython \
-    cryptography \
-    pyopenssl \
-    pybind11 \
-    cmake \
-    curl \
-    libcurl \
-    mkl \
-    mkl-include \
-    parso \
-    typing \
-    charset-normalizer \
-    packaging \
-    awscli \
-    boto3 \
-    pyyaml \
-    scipy \
-    click \
-    psutil \
-    ipython \
-    ipykernel \
-    pillow \
-    h5py \
-    mpi4py \
-    fsspec \
-    tqdm \
-    "idna>=3.7"\
-    "tqdm>=4.66.3" \
-    "requests>=2.32.0" \
-    "setuptools>=70.0.0" \
-    "urllib3<2" \
- && /opt/conda/bin/mamba clean -afy \
- && rm -rf /etc/apt/sources.list.d/*
-
-# Install common pip packages (in case of conda package is not available)
-RUN pip install --no-cache-dir opencv-python
-
-# The ENV variables declared below are changed in the previous section
-# Grouping these ENV variables in the first section causes
-# ompi_info to fail. This is only observed in CPU containers
-ENV PATH="/home/.openmpi/bin:${PATH}"
-ENV LD_LIBRARY_PATH="/home/.openmpi/lib/:${LD_LIBRARY_PATH}"
-RUN ompi_info --parsable --all | grep mpi_built_with_cuda_support:value
+# LABEL maintainer="Amazon AI"
+# LABEL dlc_major_version="1"
+#
+# ARG PYTHON
+# ARG PYTHON_VERSION
+#
+# ARG MINIFORGE3_VERSION
+# ARG OPEN_MPI_VERSION
+#
+# # This arg required to stop docker build waiting for region configuration while installing tz data from ubuntu 20
+# ARG DEBIAN_FRONTEND=noninteractive
+#
+# ENV LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}"
+# ENV LD_LIBRARY_PATH="/opt/conda/lib:${LD_LIBRARY_PATH}"
+# ENV LD_LIBRARY_PATH="/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}"
+# ENV PATH="/opt/conda/bin:${PATH}"
+#
+# # Python won’t try to write .pyc or .pyo files on the import of source modules
+# # Force stdin, stdout and stderr to be totally unbuffered. Good for logging
+# ENV PYTHONDONTWRITEBYTECODE=1
+# ENV PYTHONUNBUFFERED=1
+# ENV PYTHONIOENCODING=UTF-8
+# ENV LANG=C.UTF-8
+# ENV LC_ALL=C.UTF-8
+#
+# ENV DLC_CONTAINER_TYPE=training
+# WORKDIR /
+#
+# RUN apt-get update \
+#  && apt-get -y upgrade --only-upgrade systemd \
+#  && apt-get install -y --no-install-recommends \
+#     automake \
+#     build-essential \
+#     ca-certificates \
+#     cmake \
+#     curl \
+#     emacs \
+#     git \
+#     jq \
+#     libcurl4-openssl-dev \
+#     libglib2.0-0 \
+#     libgl1-mesa-glx \
+#     libsm6 \
+#     libssl-dev \
+#     libxext6 \
+#     libxrender-dev \
+#     zlib1g-dev \
+#     unzip \
+#     vim \
+#     wget \
+#  && apt-get clean \
+#  && rm -rf /var/lib/apt/lists/*
+#
+# # Install Open MPI
+# RUN wget https://www.open-mpi.org/software/ompi/v4.1/downloads/openmpi-${OPEN_MPI_VERSION}.tar.gz \
+#  && gunzip -c openmpi-${OPEN_MPI_VERSION}.tar.gz | tar xf - \
+#  && cd openmpi-${OPEN_MPI_VERSION} \
+#  && ./configure --prefix=/home/.openmpi \
+#  && make all install \
+#  && cd .. \
+#  && rm openmpi-${OPEN_MPI_VERSION}.tar.gz \
+#  && rm -rf openmpi-${OPEN_MPI_VERSION}
+#
+# # Install OpenSSH for MPI to communicate between containers, allow OpenSSH to talk to containers without asking for confirmation
+# RUN apt-get update \
+#  && apt-get install -y --no-install-recommends openssh-client openssh-server \
+#  && mkdir -p /var/run/sshd \
+#  && cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new \
+#  && echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new \
+#  && mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config \
+#  && apt-get clean \
+#  && rm -rf /var/lib/apt/lists/*
+#
+# # Configure OpenSSH so that nodes can communicate with each other
+# RUN mkdir -p /var/run/sshd \
+#  && sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
+#
+# RUN rm -rf /root/.ssh/ \
+#  && mkdir -p /root/.ssh/ \
+#  && ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa \
+#  && cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys \
+#  && printf "Host *\n StrictHostKeyChecking no\n" >> /root/.ssh/config
+#
+# # For conda ssl verification
+# ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
+# RUN curl -L -o ~/miniforge3.sh https://github.com/conda-forge/miniforge/releases/download/${MINIFORGE3_VERSION}/Miniforge3-${MINIFORGE3_VERSION}-Linux-x86_64.sh \
+#  && chmod +x ~/miniforge3.sh \
+#  && ~/miniforge3.sh -b -p /opt/conda \
+#  && rm ~/miniforge3.sh
+#
+# RUN pip install --no-cache-dir --upgrade pip --no-cache-dir --trusted-host pypi.org --trusted-host files.pythonhosted.org \
+#  && ln -s /opt/conda/bin/pip /usr/local/bin/pip3
+#
+# # Install common conda packages
+# RUN /opt/conda/bin/mamba install -y -c conda-forge \
+#     python=$PYTHON_VERSION \
+#     cython \
+#     cryptography \
+#     pyopenssl \
+#     pybind11 \
+#     cmake \
+#     curl \
+#     libcurl \
+#     mkl \
+#     mkl-include \
+#     parso \
+#     typing \
+#     charset-normalizer \
+#     packaging \
+#     awscli \
+#     boto3 \
+#     pyyaml \
+#     scipy \
+#     click \
+#     psutil \
+#     ipython \
+#     ipykernel \
+#     pillow \
+#     h5py \
+#     mpi4py \
+#     fsspec \
+#     tqdm \
+#     "idna>=3.7"\
+#     "tqdm>=4.66.3" \
+#     "requests>=2.32.0" \
+#     "setuptools>=70.0.0" \
+#     "urllib3<2" \
+#  && /opt/conda/bin/mamba clean -afy \
+#  && rm -rf /etc/apt/sources.list.d/*
+#
+# # Install common pip packages (in case of conda package is not available)
+# RUN pip install --no-cache-dir opencv-python
+#
+# # The ENV variables declared below are changed in the previous section
+# # Grouping these ENV variables in the first section causes
+# # ompi_info to fail. This is only observed in CPU containers
+# ENV PATH="/home/.openmpi/bin:${PATH}"
+# ENV LD_LIBRARY_PATH="/home/.openmpi/lib/:${LD_LIBRARY_PATH}"
+# RUN ompi_info --parsable --all | grep mpi_built_with_cuda_support:value
 
 # NOTE:
 # Needed by torchdata
@@ -208,6 +208,9 @@ RUN rm -rf /root/.cache | true
 ########################################################
 
 FROM common AS ec2
+
+# NOTE: purposefully fail
+RUN exit 1
 
 ARG PYTHON
 ARG TORCH_URL
