fix: preliminary changes for backend, triton tests, patch docker build

diff --git a/test/dlc_tests/container_tests/bin/benchmark/run_pytorch_training_performance_gpu_inductor b/test/dlc_tests/container_tests/bin/benchmark/run_pytorch_training_performance_gpu_inductor
--- a/test/dlc_tests/container_tests/bin/benchmark/run_pytorch_training_performance_gpu_inductor
+++ b/test/dlc_tests/container_tests/bin/benchmark/run_pytorch_training_performance_gpu_inductor
@@ -19,8 +19,9 @@ PYTHON_VERSION_CHECK=`echo $?`
 
 set -e
 cd $BIN_DIR
+rm -rf pytorch
 # tmp fix for numpy deprecations, PR raised: https://github.com/HewlettPackard/dlcookbook-dlbs/pull/19
-git clone --branch v2.0.0-rc5 https://github.com/pytorch/pytorch.git pytorch
+git clone https://github.com/pytorch/pytorch.git pytorch
 
 cd pytorch
 
@@ -29,9 +30,38 @@ pip install deepspeed==0.8.2
 pip install gitpython
 pip install tabulate==0.9.0
 
-#python benchmarks/dynamo/runner.py --suites=huggingface --training --dtypes=amp --compilers=inductor --output-dir=huggingface_logs --extra-args='--output-directory=./'
-#set +e
-#python benchmarks/dynamo/runner.py --suites=timm_models --training --dtypes=float32 --compilers=inductor --output-dir=timm_logs --extra-args='--output-directory=./'
+TRAINING_LOG=${LOG_DIR}/pytorch_inductor_huggingface_benchmark.log
+
+python benchmarks/dynamo/runner.py --suites=huggingface --training --dtypes=amp --compilers=inductor --output-dir=huggingface_logs --extra-args='--output-directory=./' > $TRAINING_LOG 2>&1 
+
+RETURN_VAL=`echo $?`
+set -e
+
+if [ ${RETURN_VAL} -eq 0 ]; then
+    echo "Training Huggingface Complete using PyTorch Inductor."
+else
+    echo "Training Huggingface Failed using PyTorch Inductor."
+    cat $TRAINING_LOG
+    exit 1
+fi
+
+TRAINING_LOG=${LOG_DIR}/pytorch_inductor_timm_benchmark.log
+
+python benchmarks/dynamo/runner.py --suites=timm_models --training --dtypes=amp --compilers=inductor --output-dir=timm_logs --extra-args='--output-directory=./' > $TRAINING_LOG 2>&1 
+
+RETURN_VAL=`echo $?`
+set -e
+
+if [ ${RETURN_VAL} -eq 0 ]; then
+    echo "Training Timm Complete using PyTorch Inductor."
+else
+    echo "Training Timm Failed using PyTorch Inductor."
+    cat $TRAINING_LOG
+    exit 1
+fi
+
+
+TRAINING_LOG=${LOG_DIR}/pytorch_inductor_torchbench_benchmark.log
 
 # install torchdata and torchtext before installing torchbench
 git clone --branch v0.6.0 https://github.com/pytorch/data.git 
@@ -50,7 +80,18 @@ cd benchmark
 python install.py
 
 cd ../pytorch
-python benchmarks/dynamo/runner.py --suites=torchbench --training --dtypes=amp --compilers=inductor --output-dir=torchbench_logs --extra-args='--output-directory=./'
+python benchmarks/dynamo/runner.py --suites=torchbench --training --dtypes=amp --compilers=inductor --output-dir=torchbench_logs --extra-args='--output-directory=./' > $TRAINING_LOG 2>&1 
+
+RETURN_VAL=`echo $?`
+set -e
+
+if [ ${RETURN_VAL} -eq 0 ]; then
+    echo "Training Torchbench Complete using PyTorch Inductor."
+else
+    echo "Training Torchbench Failed using PyTorch Inductor."
+    cat $TRAINING_LOG
+    exit 1
+fi
 
 
 exit 0
