try timm logging

diff --git a/test/dlc_tests/container_tests/bin/benchmark/run_pytorch_inductor_training_benchmark_gpu_huggingface b/test/dlc_tests/container_tests/bin/benchmark/run_pytorch_inductor_training_benchmark_gpu_huggingface
--- a/test/dlc_tests/container_tests/bin/benchmark/run_pytorch_inductor_training_benchmark_gpu_huggingface
+++ b/test/dlc_tests/container_tests/bin/benchmark/run_pytorch_inductor_training_benchmark_gpu_huggingface
@@ -23,7 +23,7 @@ pip install -U numpy
 pip install gitpython
 pip install tabulate==0.9.0
 
-#TRAINING_LOG=${LOG_DIR}/pytorch_inductor_huggingface_benchmark.log
+TRAINING_LOG=${LOG_DIR}/pytorch_inductor_huggingface_benchmark.log
 
 if [ "$1" = "p3.2xlarge" ]; then
   export INSTANCE_TYPE="p3.2xlarge"
@@ -39,25 +39,20 @@ else
   echo "No need to adjust batch size since we are using p4d.24xlarge."
 fi
 
-#rm -rf $BIN_DIR/pytorch/huggingface_logs
-#mkdir -p $BIN_DIR/pytorch/huggingface_logs
-#python $BIN_DIR/pytorch/benchmarks/dynamo/huggingface.py --performance --amp -dcuda --output=huggingface_logs/inductor_huggingface_amp_training_cuda_performance.csv --training --inductor --output-directory=$BIN_DIR/pytorch/ --no-skip --dashboard -x GPTJForCausalLM -x Reformer -x GPTJForQuestionAnswering -x GPTNeoForSequenceClassification -x BlenderbotForConditionalGeneration -x GPTNeoForCausalLM --cold-start-latency
-#python $BIN_DIR/pytorch/benchmarks/dynamo/huggingface.py --accuracy --amp -dcuda --output=huggingface_logs/inductor_huggingface_amp_training_cuda_accuracy.csv --training --inductor --output-directory=$BIN_DIR/pytorch/ --no-skip --dashboard -x GPTJForCausalLM -x Reformer -x GPTJForQuestionAnswering -x GPTNeoForSequenceClassification -x BlenderbotForConditionalGeneration -x GPTNeoForCausalLM --cold-start-latency 
-
 cd $BIN_DIR/pytorch
 
-python benchmarks/dynamo/runner.py --training --suites=huggingface --dtypes=amp --compilers=inductor --output-dir=huggingface_logs --extra-args='--output-directory=./' 
+python benchmarks/dynamo/runner.py --training --suites=huggingface --dtypes=amp --compilers=inductor --output-dir=huggingface_logs --extra-args='--output-directory=./' 2>&1 | tee $TRAINING_LOG
 
-#RETURN_VAL=`echo $?`
-#set -e
+RETURN_VAL=`echo $?`
+set -e
 
-#if [ ${RETURN_VAL} -eq 0 ]; then
-#    echo "Benchmarking Huggingface Training Complete using PyTorch Inductor."
-#else
-#    echo "Benchmarking Huggingface Training Failed using PyTorch Inductor."
-#    cat $TRAINING_LOG
-#    exit 1
-#fi
+if [ ${RETURN_VAL} -eq 0 ]; then
+    echo "Benchmarking Huggingface Training Complete using PyTorch Inductor."
+else
+    echo "Benchmarking Huggingface Training Failed using PyTorch Inductor."
+    cat $TRAINING_LOG
+    exit 1
+fi
 
 python /test/bin/benchmark/read_upload_benchmarking_results.py -dir $BIN_DIR/pytorch/huggingface_logs \
        -model_suite huggingface -precision amp
diff --git a/test/dlc_tests/container_tests/bin/benchmark/run_pytorch_inductor_training_benchmark_gpu_timm b/test/dlc_tests/container_tests/bin/benchmark/run_pytorch_inductor_training_benchmark_gpu_timm
--- a/test/dlc_tests/container_tests/bin/benchmark/run_pytorch_inductor_training_benchmark_gpu_timm
+++ b/test/dlc_tests/container_tests/bin/benchmark/run_pytorch_inductor_training_benchmark_gpu_timm
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-export INSTANCE_TYPE=$1
-
 PYTHON_VERSION=$(python -c 'import sys; print(sys.version_info[0])' | tr -d "'")
 if [ "$PYTHON_VERSION" -eq 2 ]
 then
@@ -25,34 +23,37 @@ pip install -U numpy
 pip install gitpython
 pip install tabulate==0.9.0
 
-#TRAINING_LOG=${LOG_DIR}/pytorch_inductor_timm_benchmark.log
+TRAINING_LOG=${LOG_DIR}/pytorch_inductor_timm_benchmark.log
 
-#if [[$1 -eq "p3.2xlarge" || $1 -eq "g4dn.4xlarge"]]; then
-sed -i "s/BATCH_SIZE_KNOWN_MODELS\[model_name\] = batch_size/BATCH_SIZE_KNOWN_MODELS[model_name] = batch_size \/ 4 if batch_size >= 4 else 1/g" $BIN_DIR/pytorch/benchmarks/dynamo/timm_models.py
-#elif [[$1 -eq "g5.4xlarge"]]; then
-#    sed -i "s/BATCH_SIZE_KNOWN_MODELS\[model_name\] = batch_size/BATCH_SIZE_KNOWN_MODELS[model_name] = batch_size \/ 2 if batch_size >= 2 else 1/g" $BIN_DIR/pytorch/benchmarks/dynamo/timm_models.py
-#else
-#    echo "No need to adjust batch size since we are using p4d.24xlarge."
-#fi
+if [ "$1" = "p3.2xlarge" ]; then
+  export INSTANCE_TYPE="p3.2xlarge"
+  sed -i "s/BATCH_SIZE_KNOWN_MODELS\[model_name\] = batch_size/BATCH_SIZE_KNOWN_MODELS[model_name] = batch_size \/ 4 if batch_size >= 4 else 1/g" $BIN_DIR/pytorch/benchmarks/dynamo/timm_models.py
+elif [ "$1" = "g4dn.4xlarge" ]; then
+  export INSTANCE_TYPE="g4dn.4xlarge"
+  sed -i "s/BATCH_SIZE_KNOWN_MODELS\[model_name\] = batch_size/BATCH_SIZE_KNOWN_MODELS[model_name] = batch_size \/ 4 if batch_size >= 4 else 1/g" $BIN_DIR/pytorch/benchmarks/dynamo/timm_models.py
+elif [ "$1" = "g5.4xlarge" ]; then
+  export INSTANCE_TYPE="g5.4xlarge"
+  sed -i "s/BATCH_SIZE_KNOWN_MODELS\[model_name\] = batch_size/BATCH_SIZE_KNOWN_MODELS[model_name] = batch_size \/ 2 if batch_size >= 2 else 1/g" $BIN_DIR/pytorch/benchmarks/dynamo/timm_models.py
+else
+  export INSTANCE_TYPE="p4d.24xlarge"
+  echo "No need to adjust batch size since we are using p4d.24xlarge."
+fi
 
-rm -rf $BIN_DIR/pytorch/timm_logs
-mkdir -p $BIN_DIR/pytorch/timm_logs
-python $BIN_DIR/pytorch/benchmarks/dynamo/timm_models.py --performance --amp -dcuda --output=timm_logs/inductor_timm_amp_training_cuda_performance.csv --training --inductor --output-directory=$BIN_DIR/pytorch/ --no-skip --dashboard -x GPTJForCausalLM -x Reformer -x GPTJForQuestionAnswering -x GPTNeoForSequenceClassification -x BlenderbotForConditionalGeneration -x GPTNeoForCausalLM --cold-start-latency
-#python $BIN_DIR/pytorch/benchmarks/dynamo/timm_models.py --accuracy --amp -dcuda --output=timm_logs/inductor_timm_amp_training_cuda_accuracy.csv --training --inductor --output-directory=$BIN_DIR/pytorch/ --no-skip --dashboard -x GPTJForCausalLM -x Reformer -x GPTJForQuestionAnswering -x GPTNeoForSequenceClassification -x BlenderbotForConditionalGeneration -x GPTNeoForCausalLM --cold-start-latency
+python benchmarks/dynamo/runner.py --training --suites=timm_models --dtypes=amp --compilers=inductor --output-dir=huggingface_logs --extra-args='--output-directory=./' 2>&1 | tee $TRAINING_LOG
 
-#RETURN_VAL=`echo $?`
-#set -e
+RETURN_VAL=`echo $?`
+set -e
 
-#if [ ${RETURN_VAL} -eq 0 ]; then
-#    echo "Training Timm Complete using PyTorch Inductor."
-#else
-#    echo "Training Timm Failed using PyTorch Inductor."
-#    cat $TRAINING_LOG
-#    exit 1
-#fi
+if [ ${RETURN_VAL} -eq 0 ]; then
+    echo "Training Timm Complete using PyTorch Inductor."
+else
+    echo "Training Timm Failed using PyTorch Inductor."
+    cat $TRAINING_LOG
+    exit 1
+fi
 
 python /test/bin/benchmark/read_upload_benchmarking_results.py -dir $BIN_DIR/pytorch/timm_logs \
-       -model_suite timm -precision amp -instance_type $1
+       -model_suite timm -precision amp
 
 
 exit 0
