only test speedup and comp_time for sanity check

diff --git a/test/dlc_tests/container_tests/bin/benchmark/run_pytorch_inductor_training_benchmark_gpu_huggingface b/test/dlc_tests/container_tests/bin/benchmark/run_pytorch_inductor_training_benchmark_gpu_huggingface
--- a/test/dlc_tests/container_tests/bin/benchmark/run_pytorch_inductor_training_benchmark_gpu_huggingface
+++ b/test/dlc_tests/container_tests/bin/benchmark/run_pytorch_inductor_training_benchmark_gpu_huggingface
@@ -37,18 +37,18 @@ sed -i "s/BATCH_SIZE_KNOWN_MODELS\[model_name\] = batch_size/BATCH_SIZE_KNOWN_MO
 rm -rf $BIN_DIR/pytorch/huggingface_logs
 mkdir -p $BIN_DIR/pytorch/huggingface_logs
 python $BIN_DIR/pytorch/benchmarks/dynamo/huggingface.py --performance --amp -dcuda --output=huggingface_logs/inductor_huggingface_amp_training_cuda_performance.csv --training --inductor --output-directory=$BIN_DIR/pytorch/ --no-skip --dashboard -x GPTJForCausalLM -x Reformer -x GPTJForQuestionAnswering -x GPTNeoForSequenceClassification -x BlenderbotForConditionalGeneration -x GPTNeoForCausalLM --cold-start-latency 
-python $BIN_DIR/pytorch/benchmarks/dynamo/huggingface.py --accuracy --amp -dcuda --output=huggingface_logs/inductor_huggingface_amp_training_cuda_accuracy.csv --training --inductor --output-directory=$BIN_DIR/pytorch/ --no-skip --dashboard -x GPTJForCausalLM -x Reformer -x GPTJForQuestionAnswering -x GPTNeoForSequenceClassification -x BlenderbotForConditionalGeneration -x GPTNeoForCausalLM --cold-start-latency 
+#python $BIN_DIR/pytorch/benchmarks/dynamo/huggingface.py --accuracy --amp -dcuda --output=huggingface_logs/inductor_huggingface_amp_training_cuda_accuracy.csv --training --inductor --output-directory=$BIN_DIR/pytorch/ --no-skip --dashboard -x GPTJForCausalLM -x Reformer -x GPTJForQuestionAnswering -x GPTNeoForSequenceClassification -x BlenderbotForConditionalGeneration -x GPTNeoForCausalLM --cold-start-latency 
 
-RETURN_VAL=`echo $?`
-set -e
+#RETURN_VAL=`echo $?`
+#set -e
 
-if [ ${RETURN_VAL} -eq 0 ]; then
-    echo "Training Huggingface Complete using PyTorch Inductor."
-else
-    echo "Training Huggingface Failed using PyTorch Inductor."
-    cat $TRAINING_LOG
-    exit 1
-fi
+#if [ ${RETURN_VAL} -eq 0 ]; then
+#    echo "Training Huggingface Complete using PyTorch Inductor."
+#else
+#    echo "Training Huggingface Failed using PyTorch Inductor."
+#    cat $TRAINING_LOG
+#    exit 1
+#fi
 
 python $HOME_DIR/read_upload_benchmarking_results.py -dir $BIN_DIR/pytorch/huggingface_logs \
        -model_suite huggingface -precision amp -instance_type $1
