add pytest cache
Signed-off-by: sirutBuasai <sirutbuasai27@outlook.com>

diff --git a/.github/workflows/pr-sglang.yml b/.github/workflows/pr-sglang.yml
--- a/.github/workflows/pr-sglang.yml
+++ b/.github/workflows/pr-sglang.yml
@@ -77,123 +77,123 @@ jobs:
           docker push ${IMAGE_URI}
           docker rmi ${IMAGE_URI}
 
-  sglang-local-benchmark-test:
-    needs: [build-sglang-image]
-    if: needs.build-sglang-image.result == 'success'
-    runs-on:
-      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
-        fleet:x86-g6xl-runner
-    steps:
-      - name: Checkout DLC source
-        uses: actions/checkout@v5
-
-      - name: Container pull
-        uses: ./.github/actions/ecr-authenticate
-        with:
-          aws_region: ${{ vars.AWS_REGION }}
-          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
-          image_uri: ${{ needs.build-sglang-image.outputs.image-uri }}
-
-      - name: Setup for SGLang datasets
-        run: |
-          mkdir -p /tmp/sglang/dataset
-          if [ ! -f /tmp/sglang/dataset/ShareGPT_V3_unfiltered_cleaned_split.json ]; then
-              echo "Downloading ShareGPT dataset..."
-              wget -P /tmp/sglang/dataset https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered/resolve/main/ShareGPT_V3_unfiltered_cleaned_split.json
-          else
-              echo "ShareGPT dataset already exists. Skipping download."
-          fi
-
-      - name: Start container
-        run: |
-          CONTAINER_ID=$(docker run -d -it --rm --gpus=all \
-            -v ${HOME}/.cache/huggingface:/root/.cache/huggingface \
-            -v /tmp/sglang/dataset:/dataset \
-            -p 30000:30000 \
-            -e SM_SGLANG_MODEL_PATH=Qwen/Qwen3-0.6B \
-            -e SM_SGLANG_REASONING_PARSER=qwen3 \
-            -e SM_SGLANG_HOST=127.0.0.1 \
-            -e SM_SGLANG_PORT=30000 \
-            -e HF_TOKEN=${{ secrets.HUGGING_FACE_HUB_TOKEN }} \
-            ${{ needs.build-sglang-image.outputs.image-uri }})
-          echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
-          echo "Waiting for container startup ..."
-          sleep 60s
-          docker logs ${CONTAINER_ID}
-
-      - name: Run SGLang tests
-        run: |
-          docker exec ${CONTAINER_ID} python3 -m sglang.bench_serving \
-          --backend sglang \
-          --host 127.0.0.1 --port 30000 \
-          --num-prompts 1000 \
-          --model Qwen/Qwen3-0.6B \
-          --dataset-name sharegpt \
-          --dataset-path /dataset/ShareGPT_V3_unfiltered_cleaned_split.json
-
-      - name: Cleanup container and images
-        if: always()
-        uses: ./.github/actions/container-cleanup
-        with:
-          container_id: ${{ env.CONTAINER_ID }}
-
-  sglang-lang-test:
-    needs: [build-sglang-image]
-    if: needs.build-sglang-image.result == 'success'
-    runs-on:
-      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
-        fleet:x86-g6exl-runner
-    steps:
-      - name: Checkout DLC source
-        uses: actions/checkout@v5
-
-      - name: Container pull
-        uses: ./.github/actions/ecr-authenticate
-        with:
-          aws_region: ${{ vars.AWS_REGION }}
-          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
-          image_uri: ${{ needs.build-sglang-image.outputs.image-uri }}
-
-      - name: Checkout SGLang tests
-        uses: actions/checkout@v5
-        with:
-          repository: sgl-project/sglang
-          ref: v0.5.5
-          path: sglang_source
-
-      - name: Start container
-        run: |
-          CONTAINER_ID=$(docker run -d -it --rm --gpus=all --entrypoint /bin/bash \
-            -v ${HOME}/.cache/huggingface:/root/.cache/huggingface \
-            -v ./sglang_source:/workdir --workdir /workdir \
-            -e HF_TOKEN=${{ secrets.HUGGING_FACE_HUB_TOKEN }} \
-            ${{ needs.build-sglang-image.outputs.image-uri }})
-          echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
-
-      - name: Setup for SGLang tests
-        run: |
-          docker exec ${CONTAINER_ID} sh -c '
-            set -eux
-
-            bash scripts/ci/ci_install_dependency.sh
-          '
-
-      - name: Run SGLang tests
-        run: |
-          docker exec ${CONTAINER_ID} sh -c '
-            set -eux
-            nvidia-smi
-
-            # Frontend Test
-            cd /workdir/test/lang
-            python3 run_suite.py --suite per-commit
-          '
-
-      - name: Cleanup container and images
-        if: always()
-        uses: ./.github/actions/container-cleanup
-        with:
-          container_id: ${{ env.CONTAINER_ID }}
+  # sglang-local-benchmark-test:
+  #   needs: [build-sglang-image]
+  #   if: needs.build-sglang-image.result == 'success'
+  #   runs-on:
+  #     - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
+  #       fleet:x86-g6xl-runner
+  #   steps:
+  #     - name: Checkout DLC source
+  #       uses: actions/checkout@v5
+  #
+  #     - name: Container pull
+  #       uses: ./.github/actions/ecr-authenticate
+  #       with:
+  #         aws_region: ${{ vars.AWS_REGION }}
+  #         aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
+  #         image_uri: ${{ needs.build-sglang-image.outputs.image-uri }}
+  #
+  #     - name: Setup for SGLang datasets
+  #       run: |
+  #         mkdir -p /tmp/sglang/dataset
+  #         if [ ! -f /tmp/sglang/dataset/ShareGPT_V3_unfiltered_cleaned_split.json ]; then
+  #             echo "Downloading ShareGPT dataset..."
+  #             wget -P /tmp/sglang/dataset https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered/resolve/main/ShareGPT_V3_unfiltered_cleaned_split.json
+  #         else
+  #             echo "ShareGPT dataset already exists. Skipping download."
+  #         fi
+  #
+  #     - name: Start container
+  #       run: |
+  #         CONTAINER_ID=$(docker run -d -it --rm --gpus=all \
+  #           -v ${HOME}/.cache/huggingface:/root/.cache/huggingface \
+  #           -v /tmp/sglang/dataset:/dataset \
+  #           -p 30000:30000 \
+  #           -e SM_SGLANG_MODEL_PATH=Qwen/Qwen3-0.6B \
+  #           -e SM_SGLANG_REASONING_PARSER=qwen3 \
+  #           -e SM_SGLANG_HOST=127.0.0.1 \
+  #           -e SM_SGLANG_PORT=30000 \
+  #           -e HF_TOKEN=${{ secrets.HUGGING_FACE_HUB_TOKEN }} \
+  #           ${{ needs.build-sglang-image.outputs.image-uri }})
+  #         echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
+  #         echo "Waiting for container startup ..."
+  #         sleep 60s
+  #         docker logs ${CONTAINER_ID}
+  #
+  #     - name: Run SGLang tests
+  #       run: |
+  #         docker exec ${CONTAINER_ID} python3 -m sglang.bench_serving \
+  #         --backend sglang \
+  #         --host 127.0.0.1 --port 30000 \
+  #         --num-prompts 1000 \
+  #         --model Qwen/Qwen3-0.6B \
+  #         --dataset-name sharegpt \
+  #         --dataset-path /dataset/ShareGPT_V3_unfiltered_cleaned_split.json
+  #
+  #     - name: Cleanup container and images
+  #       if: always()
+  #       uses: ./.github/actions/container-cleanup
+  #       with:
+  #         container_id: ${{ env.CONTAINER_ID }}
+  #
+  # sglang-lang-test:
+  #   needs: [build-sglang-image]
+  #   if: needs.build-sglang-image.result == 'success'
+  #   runs-on:
+  #     - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
+  #       fleet:x86-g6exl-runner
+  #   steps:
+  #     - name: Checkout DLC source
+  #       uses: actions/checkout@v5
+  #
+  #     - name: Container pull
+  #       uses: ./.github/actions/ecr-authenticate
+  #       with:
+  #         aws_region: ${{ vars.AWS_REGION }}
+  #         aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
+  #         image_uri: ${{ needs.build-sglang-image.outputs.image-uri }}
+  #
+  #     - name: Checkout SGLang tests
+  #       uses: actions/checkout@v5
+  #       with:
+  #         repository: sgl-project/sglang
+  #         ref: v0.5.5
+  #         path: sglang_source
+  #
+  #     - name: Start container
+  #       run: |
+  #         CONTAINER_ID=$(docker run -d -it --rm --gpus=all --entrypoint /bin/bash \
+  #           -v ${HOME}/.cache/huggingface:/root/.cache/huggingface \
+  #           -v ./sglang_source:/workdir --workdir /workdir \
+  #           -e HF_TOKEN=${{ secrets.HUGGING_FACE_HUB_TOKEN }} \
+  #           ${{ needs.build-sglang-image.outputs.image-uri }})
+  #         echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
+  #
+  #     - name: Setup for SGLang tests
+  #       run: |
+  #         docker exec ${CONTAINER_ID} sh -c '
+  #           set -eux
+  #
+  #           bash scripts/ci/ci_install_dependency.sh
+  #         '
+  #
+  #     - name: Run SGLang tests
+  #       run: |
+  #         docker exec ${CONTAINER_ID} sh -c '
+  #           set -eux
+  #           nvidia-smi
+  #
+  #           # Frontend Test
+  #           cd /workdir/test/lang
+  #           python3 run_suite.py --suite per-commit
+  #         '
+  #
+  #     - name: Cleanup container and images
+  #       if: always()
+  #       uses: ./.github/actions/container-cleanup
+  #       with:
+  #         container_id: ${{ env.CONTAINER_ID }}
 
   sglang-sagemaker-test:
     needs: [build-sglang-image]
